---
- hosts: localhost
  vars:
    url_list:
      - url: https://jsonplaceholder.typicode.com/users
        status: 200
        content: mail
      - url: https://jsonplaceholder.typicode.com/users
        status: 200
    result: ok
  tasks:
    - name: check url 
      block:
        - name: send url request
          uri:
            url: "{{ item.url }}"
            # username: user
            # password: passwd
            # force_basic_auth: yes
            return_content: yes
            timeout: 10
            status_code: "{{ item.status }}"
          register: content
          with_items: "{{ url_list }}"
          delegate_to: localhost
          when: item.content is not defined
        
        - name: send url request and also check return content
          uri:
            url: "{{ item.url }}"
            # username: user
            # password: passwd
            # force_basic_auth: yes
            return_content: yes
            timeout: 10
            status_code: "{{ item.status }}"
          register: this
          with_items: "{{ url_list }}"
          failed_when: "item.content not in this.content"
          delegate_to: localhost
          when: item.content is defined
      rescue:
        - set_fact:
            result: failed
        - debug:
            msg: 
        - fail: 
            msg: error is happened
          when: result == "failed"
        - name:  
          debug:
            msg: 'I also never execute :-('
      always:
        - name: always to check result
          debug:
            msg: "all tasks are finished, result is {{ result }}"          
