---
- hosts: all
  # become: true
  vars_files:
    - vars.yml   # tasks file for audit
  tasks:
    - name: check url 
      uri:
        url: "{{ item.url }}"
        # username: user
        # password: passwd
        # force_basic_auth: yes
        return_content: yes
      register: jsoncontent
      with_items: "{{ url_list }}"