---
- hosts: localhost
  # become: true
  vars_files:
    - vars.yml  
  tasks:
    - name: Check if port is listening
      block:
        - name: do checking
          wait_for:
            port: "{{ item.name }}"
            delay: 0
            timeout: 5
            msg: "Timeout waiting for {{ item.name }} to respond"
          register: port_check
          # ignore_errors: yes
          with_items: "{{ check_port }}"
        
      rescue:
        - debug:  
            msg: "error is happened {{result}}"
        - set_fact:
            result: failed
      
      always:
        - name: always to check result
          fail: 
            msg: error is happened
          when: result == "failed"
    - name:  
      fail: 
        msg: error is happened
      when: result == "failed"

    - name:  
      debug:
        msg: all is ok