---
- hosts: all
  vars:
    check_port:
      - 8080
      - 80
    result: ok
  tasks:
    - name: Check if port is listening
      block:
        - name: do checking....
          wait_for:
            port: "{{ item }}"
            timeout: 5
            msg: "Timeout waiting for {{ item }} to respond"
          loop: "{{ check_port }}"
      rescue:
        - set_fact:
            result: failed
        - fail: 
            msg: error is happened
          when: result == "failed"
        - name:  
          debug:
            msg: 'I also never execute :-('
      always:
        - name: always to check result
          debug:
            msg: "all is finished, result is {{ result }}"  