---
- name: loop to check service status
  hosts: all
  gather_facts: no
  vars:
    service_list:
      - name: netconsole
        status: running
      - name: firewalld.service
        status: running
    result: ok
  tasks:
    - name: Gathering service facts
      service_facts:
      register: services_state

    - name: print all of service status
      debug: var=services_state.ansible_facts.services

    - name: loop for get detail of service
      block:
        - assert: 
            that:
              - item.name in services
              - services[item.name].state == item.status
            fail_msg: "{{ item.name }} is not in status {{ item.status }}" 
            msg: "{{ item.name }} is in status {{ item.status }}" 
          vars:
            services: "{{ services_state.ansible_facts.services }}"
          # ignore_errors: true
          with_items: "{{ service_list }}"
      rescue:
        - set_fact:
            result: failed
        - fail: 
            msg: error is happened
          when: result == "failed"
        - name:  
          debug:
            msg: 'I also never execute :-('
      always:
        - name: always to check result
          debug:
            msg: "all tasks are finished, result is {{ result }}"          
    