---
- hosts: all
  # become: true
  vars_files:
    - vars.yml  
  tasks:
    - name: Check if port is listening
      block:
        - name: hello
          wait_for:
            port: "{{ item.name }}"
            delay: 0
            timeout: 10
            msg: "Timeout waiting for {{ item.name }} to respond"
          register: port_check
          ignore_errors: yes
          with_items: "{{ check_port }}"
      rescue:
        - debug:  
            msg: this a error is happened
          var:
            result: error
      always:
        - fail: 
            msg: error is happed
          when: result == "error"
        
    
    