---
- hosts: localhost
  # force_handlers: true
  # gather_facts: no
  vars_files:
    - vars.yml  
  tasks:
    # - name: Download JSON content play
    #   uri:
    #     url: https://jsonplaceholder.typicode.com/users
    #     # username: user
    #     # password: passwd
    #     # force_basic_auth: yes
    #     return_content: yes
    #   register: jsoncontent
    - name: read csv file to get host info
      read_csv:
        path: host.csv
        fieldnames: ip,username,password
      register: hosts
      delegate_to: localhost  

    - name: loop to call redfish rest service
      include_role:
        name: audit
      with_items: "{{ hosts.list }}"
      loop_control:
        loop_var: item
      # ignore_errors: yes

    