---
- name: test playbook 
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault-pass.yml
  vars:
    param: 80
    users:
      age:  
        state: "running"
        sdfd: "dfdf"
      error:  
        state: "running"
        sdfd: "dfdf"
    its: 
      - first:
          name: age12
          status: running
      - second:
          name: error
          status: running
  tasks:
    - name: testing vault
      debug:
        var: username
    - name: testing vault
      debug:
        msg: "Key={{ item.key }} value={{ item.value }}"
      loop: "{{ users | dict2items  }}"
    # - name: testing
    #   debug:
    #     msg: "error is happy {{ item.name }}"
    #   # failed_when: 'item.item.name not in users or users[item.item.name].state != item.status'
    #   with_items: "{{ its }}"
    #   ignore_errors: true
    # - name: testing
    #   assert:
    #     that:
    #       - param > 0
    #       - param > 100
    #     fail_msg: no need to do
    #     success_msg: ok